-- 22/02/2021 19:33:30 ART
-- ISSUE #80: Cierre de Cajas.
UPDATE AD_Column SET ColumnSQL='(SELECT (C_BankStatement.ScrutinizedCheckAmt - ((SELECT COALESCE(Sum(sl.TrxAmt),0) FROM C_BankStatementLine sl JOIN C_Payment p ON (sl.C_Payment_ID = p.C_Payment_ID) WHERE (C_BankStatement.C_BankStatement_ID = sl.C_BankStatement_ID AND p.TenderType IN (''K'',''Z'') AND p.LAR_Cheque_Emitido_ID IS NULL AND p.EsElectronico = ''N'')) + (COALESCE((SELECT SUM(pa.PayAmt) FROM C_Payment pa WHERE pa.C_BankAccount_ID=C_BankStatement.C_BankAccount_ID AND pa.IsOnDrawer=''Y'' AND pa.IsReceipt=''Y'' AND pa.DocStatus IN (''CO'',''CL'') AND pa.TenderType IN (''K'',''Z'') AND pa.EsElectronico = ''N'' AND pa.C_Payment_ID NOT IN (SELECT sli.C_Payment_ID FROM C_BankStatementLine sli WHERE C_BankStatement.C_BankStatement_ID=sli.C_BankStatement_ID)) , 0)) + (COALESCE((SELECT SUM(pa.PayAmt) FROM C_Payment pa WHERE pa.C_BankAccount_ID=C_BankStatement.C_BankAccount_ID AND pa.IsReceipt=''N'' AND pa.DocStatus IN (''CO'',''CL'') AND pa.TenderType IN (''K'',''Z'') AND pa.IsReconciled=''N'' AND pa.LAR_Cheque_Emitido_ID IS NULL AND pa.EsElectronico = ''N'' AND pa.LAR_PaymentSource_ID > 0 AND pa.LAR_PaymentSource_ID NOT IN (SELECT sli.C_Payment_ID FROM C_BankStatementLine sli WHERE C_BankStatement.C_BankStatement_ID=sli.C_BankStatement_ID)) , 0)))))',Updated=TO_TIMESTAMP('2021-02-22 19:33:30','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Column_ID=3000157
;

-- 22/02/2021 19:38:01 ART
-- ISSUE #80: Cierre de Cajas.
UPDATE AD_Column SET ColumnSQL='((SELECT COALESCE(Sum(sl.TrxAmt),0) FROM C_BankStatementLine sl  JOIN C_Payment p ON (sl.C_Payment_ID = p.C_Payment_ID) WHERE (C_BankStatement.C_BankStatement_ID = sl.C_BankStatement_ID AND p.TenderType IN (''K'',''Z'') AND p.LAR_Cheque_Emitido_ID IS NULL AND p.EsElectronico = ''N'')) + (COALESCE((SELECT SUM(pa.PayAmt) FROM C_Payment pa WHERE pa.C_BankAccount_ID=C_BankStatement.C_BankAccount_ID AND pa.IsOnDrawer=''Y'' AND pa.IsReceipt=''Y'' AND pa.DocStatus IN (''CO'',''CL'') AND pa.TenderType IN (''K'',''Z'') AND pa.EsElectronico = ''N'' AND pa.C_Payment_ID NOT IN (SELECT sli.C_Payment_ID  FROM C_BankStatementLine sli  WHERE C_BankStatement.C_BankStatement_ID=sli.C_BankStatement_ID)) , 0)) + (COALESCE((SELECT SUM(pa.PayAmt) FROM C_Payment pa  WHERE pa.C_BankAccount_ID=C_BankStatement.C_BankAccount_ID AND pa.IsReceipt=''N'' AND pa.DocStatus IN (''CO'',''CL'') AND pa.TenderType IN (''K'',''Z'') AND pa.IsReconciled=''N'' AND pa.LAR_Cheque_Emitido_ID IS NULL AND pa.EsElectronico = ''N'' AND pa.LAR_PaymentSource_ID > 0 AND pa.LAR_PaymentSource_ID NOT IN (SELECT sli.C_Payment_ID  FROM C_BankStatementLine sli  WHERE C_BankStatement.C_BankStatement_ID=sli.C_BankStatement_ID)) , 0)))',Updated=TO_TIMESTAMP('2021-02-22 19:38:01','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Column_ID=3000149
;

-- 22/02/2021 20:10:38 ART
-- ISSUE #80: Cierre de Cajas.
UPDATE AD_Column SET ColumnSQL='((SELECT (C_BankStatement.ScrutinizedCashAmt - (COALESCE(Sum(TrxAmt),0))) FROM C_BankStatementLine sl JOIN C_Payment p ON (sl.C_Payment_ID = p.C_Payment_ID) WHERE (C_BankStatement.C_BankStatement_ID = sl.C_BankStatement_ID AND p.TenderType = ''X'')) + (SELECT (C_BankStatement.ScrutinizedCheckAmt - ((SELECT COALESCE(Sum(sl.TrxAmt),0) FROM C_BankStatementLine sl  JOIN C_Payment p ON (sl.C_Payment_ID = p.C_Payment_ID) WHERE (C_BankStatement.C_BankStatement_ID = sl.C_BankStatement_ID AND p.TenderType IN (''K'',''Z'') AND p.LAR_Cheque_Emitido_ID IS NULL AND p.EsElectronico = ''N'')) + (COALESCE((SELECT SUM(pa.PayAmt)  FROM C_Payment pa WHERE pa.C_BankAccount_ID=C_BankStatement.C_BankAccount_ID AND pa.IsOnDrawer=''Y'' AND pa.IsReceipt=''Y'' AND pa.DocStatus IN (''CO'',''CL'') AND pa.TenderType IN (''K'',''Z'') AND pa.EsElectronico = ''N'' AND pa.C_Payment_ID NOT IN (SELECT sli.C_Payment_ID  FROM C_BankStatementLine sli  WHERE C_BankStatement.C_BankStatement_ID=sli.C_BankStatement_ID)) , 0)) + (COALESCE((SELECT SUM(pa.PayAmt) FROM C_Payment pa WHERE pa.C_BankAccount_ID=C_BankStatement.C_BankAccount_ID AND pa.IsReceipt=''N'' AND pa.DocStatus IN (''CO'',''CL'') AND pa.TenderType IN (''K'',''Z'') AND pa.EsElectronico = ''N'' AND pa.IsReconciled=''N'' AND pa.LAR_Cheque_Emitido_ID IS NULL AND pa.LAR_PaymentSource_ID > 0 AND pa.LAR_PaymentSource_ID NOT IN (SELECT sli.C_Payment_ID  FROM C_BankStatementLine sli  WHERE C_BankStatement.C_BankStatement_ID=sli.C_BankStatement_ID)) , 0))))) + (SELECT (C_BankStatement.ScrutinizedCreditCardAmt - (COALESCE(Sum(TrxAmt),0))) FROM C_BankStatementLine sl JOIN C_Payment p ON (sl.C_Payment_ID = p.C_Payment_ID) WHERE (C_BankStatement.C_BankStatement_ID = sl.C_BankStatement_ID AND p.TenderType IN (''D'', ''C''))) - C_BankStatement.SaldoInicial)',Updated=TO_TIMESTAMP('2021-02-22 20:10:38','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Column_ID=3000161
;

-- Registración de script
SELECT register_migration_script_lar('0164_ISSUE-80.sql', 'LAR', '')
;
